### ISSUE TITLE
My doubts

### ISSUE THREAD

**Issue by Zzzzzkk98** [elouayas/EEGSimpleConv#1]
Hello author, first of all, thank you very much for sharing, the code idea is very wonderful and clear, but I have a small question I would like to ask you, why the data in your paper is generally lower than the accuracy of the code reproduction, is it caused by the parameters? In addition, I would like to ask, what is the purpose of the "session" field in the configuration file?

**Comment by elouayas** [comment]
Hello everyone,
Thanks for the feedback!
As you noticed, there is a difference in accuracy between the paper and GitHub. 
The correct values are the ones reported in the repository (I invite you to run it, so if you can, don't hesitate to tell me if I can help you run it!). The gap was due to a small mistake I made when applying Euclidean alignment. The paper is an arXiv paper, and the final version of it (which is currently being reviewed for publication) won't contain this error! We will update the arXiv numbers as soon as possible!

Regarding the "session" field, it indicates whether the normalisation techniques we use should be applied at the subject level (False) or at the session level (True). I invite you to read section III.B.2. (the session statistics point) if you want more details!

The repository is currently missing some documentation about the configuration file ! I will update it quickly to give more clarity on how to use the configuration dict !

**Comment by Zzzzzkk98** [comment]
Thank you very much for your answers, which solved my inner doubts, and I look forward to your update and the final version of the paper.
